### ISSUE TITLE
Introduce basic VueJS rooting into ScienceDbGui

### ISSUE THREAD

**Issue by edwards33** [ScienceDb/ScienceDbGui#1] opened 2017-09-22 13:55 UTC
Use VueJS example to introduce basic VueJS rooting into the skeleton App.

Upon generating a new data model, e.g. for User, make the generated components available within the skeleton App (ScienceDbGui).

Imagine having run this command from the Shell:

admin_gui_gen --baseUrl 'localhost:3333' --name User --attributes 'email:string' .

You should then have the following new components in ScienceDbGui:

    src/components/UserCreateForm.vue
    src/components/UserCustomActions.vue
    src/components/UserDetailRow.vue
    src/components/UserEditForm.vue
    src/components/UserFormElemns.vue
    src/components/Users.vue
    src/components/foreignKeyFormElement.vue
    src/router/UserRoutes.js

Clearly stated, the task of this issue is to make the code-generated files above be integrated into the skeleton project.

**Comment by asishallab** [comment] 2017-09-29 16:09
This is a duplicate of [admin_gui_gen Issue #6](https://github.com/ScienceDb/admin_gui_gen/issues/6)

**Comment by asishallab** [comment] 2017-10-20 11:12
Closed duplicate

**Closed by asishallab** 2017-10-20 11:12 UTC
Labels: enhancement
